### ISSUE TITLE
question about the equations

### ISSUE THREAD

**Issue by speedcell4** [leuchine/S-LSTM#3]
Hi~

I noticed in your equation (2) you applied softmax for these gates before building the new cell state, `i, l, r, f, s = softmax(i, l, r, f, s)`. but I can not figure out why you need a softmax, I think you have already activated them by using sigmoid why you need another softmax. to normalize them? or for performance?

**Comment by leuchine** [comment]
Hi:

That's just for numerical stability. Since we have to add up five vectors and this is performed iteratively, the norms of the vectors maybe increase after a few iterations. Adding a softmax may help here. I did not test removing the softmax. But you can try remove it if it interests you. Thanks!

Best Regards,
Qi

**Comment by speedcell4** [comment]
but why the origin version LSTM does not count on this? I guess if the norms of the vectors maybe increase after a few iterations, the origin version LSTM should also suffer this issue.

in practice, yes, I have tried removing the softmax in my re-implementation version SentLSTM. and yes, the softmax really matters (about 0.3 drops).

**Comment by leuchine** [comment]
Hi:

Thanks a lot for your empirical results. I am not sure about the reasons here. Yet, in LSTM, it also usually uses f_t and (1 - f_t), where f_t denotes the forget  gate, to combine the new cell state and the original cell state. This is very similar to a softmax. Besides, I am also not sure whether adding a softmax will help in other datasets. Thanks!

Best Regards,
Qi
